name: windows-intelLLVM

on:     
  pull_request:
    branches:
      - main
      - dev

jobs:

  builds-and-tests:
    runs-on: windows-latest
    strategy:
      matrix: 
        optimization-type: ["Debug", "Release"]

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake build
      shell: bash
      run: |
        cmake -S . -B build -GNinja \
          -DCMAKE_BUILD_TYPE=${{matrix.optimization-type}}
        cmake --build build -j